server:
  port: 8081
spring:
  application:
    name: tfm-backend
  datasource:
    url: jdbc:h2:mem:tfm-database;Mode=MySQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true